GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
    "title": "harry porter"
}

###

PUT http://localhost:3001/books/280e HTTP/1.1
Content-Type: application/json

{
    "title": "dark tower"
}

###

DELETE http://localhost:3001/books/280e HTTP/1.1
Content-Type: application/json
